import Foundation

public enum TVRelayCopy {
    public static let pair = LocalizedString(en: "Pair iPhone or iPad", fr: "Jumeler un iPhone ou iPad", es: "Enlazar iPhone o iPad", ja: "iPhoneまたはiPadをペアリング", zh: "配对 iPhone 或 iPad", ko: "iPhone 또는 iPad 페어링", ru: "Подключить iPhone или iPad", de: "iPhone oder iPad koppeln", ar: "إقران iPhone أو iPad", it: "Abbina iPhone o iPad", pt: "Emparelhar iPhone ou iPad")
    public static let disconnect = LocalizedString(en: "Disconnect", fr: "Déconnecter", es: "Desconectar", ja: "接続解除", zh: "断开连接", ko: "연결 해제", ru: "Отключить", de: "Trennen", ar: "قطع الاتصال", it: "Disconnetti", pt: "Desligar")
    public static let cancel = LocalizedString(en: "Cancel pairing", fr: "Annuler le jumelage", es: "Cancelar enlace", ja: "ペアリングをキャンセル", zh: "取消配对", ko: "페어링 취소", ru: "Отменить сопряжение", de: "Kopplung abbrechen", ar: "إلغاء الإقران", it: "Annulla abbinamento", pt: "Cancelar emparelhamento")
    public static let waiting = LocalizedString(en: "Connected. Waiting for your session…", fr: "Connecté. En attente de votre séance…", es: "Conectado. Esperando tu sesión…", ja: "接続済み。セッションを待っています…", zh: "已连接。正在等待您的练习…", ko: "연결됨. 세션을 기다리는 중…", ru: "Подключено. Ожидание занятия…", de: "Verbunden. Warte auf deine Sitzung…", ar: "متصل. في انتظار جلستك…", it: "Connesso. In attesa della sessione…", pt: "Ligado. A aguardar a sessão…")
    public static let introduction = LocalizedString(en: "Bring your guided movement to the big screen. You choose when to share your session.", fr: "Vos mouvements guidés sur grand écran. Vous choisissez quand partager votre séance.", es: "Lleva el movimiento guiado a la pantalla grande. Tú eliges cuándo compartir tu sesión.", ja: "ガイド付きの動きを大画面へ。セッションを共有するタイミングは自分で選べます。", zh: "在大屏幕上跟随引导练习。您决定何时共享练习。", ko: "안내에 따른 움직임을 큰 화면에서 즐기세요. 세션 공유 시점은 직접 선택합니다.", ru: "Занимайтесь с подсказками на большом экране. Вы сами выбираете, когда делиться занятием.", de: "Geführte Bewegung auf dem großen Bildschirm. Du entscheidest, wann du deine Sitzung teilst.", ar: "انقل الحركة الموجّهة إلى الشاشة الكبيرة. أنت تختار وقت مشاركة جلستك.", it: "Porta il movimento guidato sul grande schermo. Scegli tu quando condividere la sessione.", pt: "Leve o movimento guiado para o grande ecrã. Escolha quando partilhar a sessão.")
    public static let instructions = LocalizedString(en: "Scan with your iPhone camera, then confirm sharing in NATURaL. Or open TV display in the app, choose this TV and enter the key below.", fr: "Scannez avec l’appareil photo de l’iPhone, puis confirmez le partage dans NATURaL. Ou ouvrez l’affichage TV dans l’app, choisissez ce téléviseur et saisissez la clé ci-dessous.", es: "Escanea con la cámara del iPhone y confirma en NATURaL. O abre la pantalla TV en la app, elige este televisor e introduce la clave.", ja: "iPhoneのカメラで読み取り、NATURaLで共有を確認します。またはアプリのTV表示でこのテレビを選び、下のキーを入力します。", zh: "使用 iPhone 相机扫描，然后在 NATURaL 中确认共享。也可以在应用的电视显示中选择此电视并输入下方密钥。", ko: "iPhone 카메라로 스캔하고 NATURaL에서 공유를 확인하세요. 또는 앱의 TV 표시에서 이 TV를 선택하고 아래 키를 입력하세요.", ru: "Сканируйте камерой iPhone и подтвердите в NATURaL. Или откройте экран ТВ в приложении, выберите этот телевизор и введите ключ.", de: "Mit der iPhone-Kamera scannen und in NATURaL bestätigen. Oder in der App TV-Anzeige öffnen, diesen Fernseher wählen und den Schlüssel eingeben.", ar: "امسح بكاميرا iPhone ثم أكّد المشاركة في NATURaL. أو افتح عرض التلفاز في التطبيق، واختر هذا التلفاز وأدخل المفتاح أدناه.", it: "Scansiona con la fotocamera di iPhone e conferma in NATURaL. Oppure apri la visualizzazione TV nell’app, scegli questa TV e inserisci la chiave.", pt: "Leia com a câmara do iPhone e confirme no NATURaL. Ou abra a opção TV na app, escolha esta TV e introduza a chave.")
    public static let expires = LocalizedString(en: "This invitation expires after 5 minutes. Keep the key private.", fr: "Cette invitation expire après 5 minutes. Gardez la clé privée.", es: "La invitación caduca en 5 minutos. Mantén la clave privada.", ja: "招待は5分で期限切れになります。キーは秘密にしてください。", zh: "邀请将在5分钟后过期。请勿泄露密钥。", ko: "초대는 5분 후 만료됩니다. 키를 비공개로 유지하세요.", ru: "Приглашение действует 5 минут. Не раскрывайте ключ.", de: "Die Einladung gilt 5 Minuten. Halte den Schlüssel geheim.", ar: "تنتهي الدعوة بعد 5 دقائق. احتفظ بسرية المفتاح.", it: "L’invito scade dopo 5 minuti. Mantieni privata la chiave.", pt: "O convite expira após 5 minutos. Mantenha a chave privada.")
    public static let unavailable = LocalizedString(en: "Pairing is unavailable. Check the local network and try again.", fr: "Jumelage indisponible. Vérifiez le réseau local et réessayez.", es: "Enlace no disponible. Comprueba la red local y vuelve a intentarlo.", ja: "ペアリングできません。ローカルネットワークを確認して再試行してください。", zh: "无法配对。请检查本地网络后重试。", ko: "페어링할 수 없습니다. 로컬 네트워크를 확인하고 다시 시도하세요.", ru: "Сопряжение недоступно. Проверьте локальную сеть и повторите.", de: "Kopplung nicht verfügbar. Prüfe das lokale Netzwerk und versuche es erneut.", ar: "الإقران غير متاح. تحقّق من الشبكة المحلية وحاول مجددًا.", it: "Abbinamento non disponibile. Controlla la rete locale e riprova.", pt: "Emparelhamento indisponível. Verifique a rede local e tente novamente.")
    public static let notFound = LocalizedString(en: "This TV is not available. Enable pairing on the TV and connect both devices to the same local network.", fr: "Ce téléviseur est introuvable. Activez le jumelage et connectez les deux appareils au même réseau local.", es: "TV no disponible. Activa el enlace y conecta ambos dispositivos a la misma red local.", ja: "テレビが見つかりません。ペアリングを有効にし、両方を同じローカルネットワークに接続してください。", zh: "找不到此电视。请启用配对并将两台设备连接到同一本地网络。", ko: "TV를 찾을 수 없습니다. 페어링을 켜고 두 기기를 같은 로컬 네트워크에 연결하세요.", ru: "Телевизор недоступен. Включите сопряжение и подключите оба устройства к одной сети.", de: "TV nicht verfügbar. Aktiviere die Kopplung und verbinde beide Geräte mit demselben lokalen Netzwerk.", ar: "التلفاز غير متاح. فعّل الإقران ووصل الجهازين بالشبكة المحلية نفسها.", it: "TV non disponibile. Attiva l’abbinamento e collega entrambi i dispositivi alla stessa rete locale.", pt: "TV indisponível. Ative o emparelhamento e ligue ambos os dispositivos à mesma rede local.")
}
